services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db_auth
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres_auth
    ports:
      - "5432:5432"
    