services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db_auth
    user: root
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api_auth
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres_auth
      SECRET: your-secret-key-change-this
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  jenkins:
    build: ./jenkins
    container_name: jenkins-ci
    user: root  # Necessário para acessar o docker.sock sem conflito de permissões
    privileged: true
    ports:
      - "8080:8080"
    environment:
      DOCKER_HOST: unix:///run/user/1000/docker.sock
      JENKINS_HOME_HOST: ./jenkins_home
      TZ: Etc/GMT+3
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /run/user/1000/docker.sock:/run/user/1000/docker.sock
    networks:
      - default
      # - kind
    restart: unless-stopped
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    restart: unless-stopped
# networks:
#   kind:
#     external: true
#     name: kind

volumes:
  postgres_data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:

networks:
  app-network:
    driver: bridge